package org.eminphis.servlets;

import java.io.IOException;
import java.io.PrintWriter;
import java.sql.SQLException;
import javax.servlet.ServletException;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.eminphis.ErrorLogger;
import org.eminphis.Printer;
import org.eminphis.db.DBManager;
import org.eminphis.dto.Appointment;
import org.eminphis.dto.Group;

/**
 * <u>e-MINPHIS</u><br>
 * A project of the Health Information Systems Unit of the<br>
 * Department of Computer Science and Engineering,<br>
 * Obafemi Awolowo University, Ile-Ife.<br>
 *
 *
 * <pre>
 * Class name: AppointmentServlet.java
 * Version: 1.0
 * Author: Essiennta Emmanuel (colourfulemmanuel@gmail.com)
 *
 * <u>Description</u>
 * Handles appointments.
 *
 * </pre>
 *
 * @author Essiennta Emmanuel (colourfulemmanuel@gmail.com)
 * @version 1.0
 */
public class AppointmentServlet extends HttpServlet{

    // <editor-fold defaultstate="collapsed" desc="HttpServlet methods. Click on the + sign on the left to edit the code.">
    /**
     * Handles the HTTP <code>GET</code> method.
     *
     * @param request  servlet request
     * @param response servlet response
     * @throws ServletException if a servlet-specific error occurs
     * @throws IOException      if an I/O error occurs
     */
    @Override
    protected void doGet(HttpServletRequest request,HttpServletResponse response)
            throws ServletException,IOException{
        response.setContentType("text/html;charset=UTF-8");
        PrintWriter out=response.getWriter();
        Integer mode=(Integer)request.getSession().getAttribute("VIEW_TYPE");
        String value;
        //retrieve the value from the search field. Check for the first non-null value.
        if((value=request.getParameter("cosultant_name"))!=null||(value=request.getParameter("clinic_name"))!=null
                ||(value=request.getParameter("date_name"))!=null);
        if(mode==null||mode!=Appointment.MODE_CLINIC&&mode!=Appointment.MODE_CONSULTANT&&mode!=Appointment.MODE_DATE
                ||value==null||value.contains("choose")||value.contains("click")){
            out.println("<h2>Invalid selection</h2>");
            return;
        }

        org.eminphis.ui.manager.AppointmentManager appointmentManager
                =new org.eminphis.ui.manager.AppointmentManager(request,response);

        appointmentManager.setMode(mode);
        appointmentManager.setValue(value);

        Group<Appointment> appointments;
        try{
            appointments=DBManager.retrieveAppointment(mode,value);
            appointmentManager.showAppointmentDetails(appointments);
        } catch(SQLException ex){
            ErrorLogger.logError(ex);
            appointmentManager.showErrorPage(
                    "An error occurred while fulfilling your request to retrieve the appointments.",ex);
        }
    }

    /**
     * Handles the HTTP <code>POST</code> method.
     *
     * @param request  servlet request
     * @param response servlet response
     * @throws ServletException if a servlet-specific error occurs
     * @throws IOException      if an I/O error occurs
     */
    @Override
    protected void doPost(HttpServletRequest request,HttpServletResponse response)
            throws ServletException,IOException{
        response.setContentType("text/html;charset=UTF-8");
        PrintWriter out=response.getWriter();
        org.eminphis.ui.manager.AppointmentManager appointmentManager
                =new org.eminphis.ui.manager.AppointmentManager(request,response);
        org.eminphis.dto.Appointment appointment=appointmentManager.retrieveAppointment();
        Printer.println("Patient name was "+appointment.getNameOfPatient());
        try{
            DBManager.insertAppointment(appointment);
            String message="<h2>The appointment was scheduled successfully.</h2>"
                    +"<body>"
                    +"Autogenerated appointment ID: "
                    +"<b>"
                    +"<font size=20>"
                    +appointment.getAppointmentId()
                    +"</font>"
                    +"</b>"
                    +"</body>";
            appointmentManager.showSuccessPage(message);
        } catch(SQLException ex){
            ErrorLogger.logError(ex);
            appointmentManager.showErrorPage(
                    "An error occurred while fulfilling your request to schedule this appointment.",ex);
        }
    }

    /**
     * Returns a short description of the servlet.
     *
     * @return a String containing servlet description
     */
    @Override
    public String getServletInfo(){
        return "Short description";
    }// </editor-fold>

}
